# Generated by Django 5.1.2 on 2024-10-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_expense', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('rent/mortgage', 'Rent/Mortgage'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('food_and_dining', 'Food and Dining'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('debt_payments', 'Debt Payments'), ('healthcare_and_medical_expenses', 'Healthcare and Medical Expenses'), ('miscellaneous_expenses', 'Miscellaneous Expenses'), ('personal_care', 'Personal Care'), ('fees', 'Fees'), ('others', 'Others')], max_length=300, null=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
