# Generated by Django 5.1.2 on 2024-10-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_expense'),
        ('vendor', '0002_rename_experience_vendor_estd_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
