# Generated by Django 5.1.3 on 2024-11-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_post_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
