# Generated by Django 5.1.3 on 2024-11-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_post_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
