# Generated by Django 5.1.3 on 2024-11-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_team_facbook_link_team_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
