# Generated by Django 5.1.2 on 2024-10-30 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_product_pro_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0.0)),
                ('order_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=555, null=True)),
                ('payment_method', models.CharField(choices=[('ssl_commerz', 'SSLCOMMERZ'), ('paypal', 'Paypal'), ('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('instamojo', 'Instamojo'), ('offlinepayment', 'Offline Payment')], max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=255)),
                ('is_ordered', models.BooleanField(default=False)),
                ('ordered_at', models.DateField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('subtotal', models.FloatField(default=0.0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
