# Generated by Django 5.1.2 on 2024-10-15 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_product_pro_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('billDate', models.DateField(blank=True, null=True)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID')], default='UNPAID', max_length=100)),
                ('discount_amount', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('other_fees_name', models.CharField(blank=True, default='Other Fees', max_length=300, null=True)),
                ('other_fees_amount', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, default='This is a computer generated invoice no need signature', null=True)),
                ('sub_total', models.FloatField(blank=True, default=0.0, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='invoice_related_items', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.FloatField(default=0.0)),
                ('sub_total', models.FloatField(default=0.0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
