# Generated by Django 5.1.2 on 2024-10-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_sub_total_alter_invoiceitem_sub_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='title',
        ),
    ]
