# Generated by Django 5.1.2 on 2024-10-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
