# Generated by Django 5.1.2 on 2024-10-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_unit_type'),
        ('vendor', '0002_rename_experience_vendor_estd_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_brand', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='category',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_category', to='vendor.vendor'),
        ),
    ]
