# Generated by Django 5.1.2 on 2024-10-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand_vendor_category_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_image',
        ),
    ]
