# Generated by Django 5.1.2 on 2024-10-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_brand_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/brands'),
        ),
    ]
