# Generated by Django 5.1.2 on 2024-10-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_type',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Both', 'Both')], max_length=1000, null=True),
        ),
    ]
